2018-04-02 10:38:23,865 : Machine : Mission Pinball Framework Core Engine v0.33.49
2018-04-02 10:38:23,866 : Machine : Command line arguments: {'create_config_cache': True, 'mc_file_name': None, 'loglevel': 11, 'mpfconfigfile': 'c:\\python34\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'logfile': 'logs\\2018-04-02-10-38-23-mpf-DESKTOP-U1P21TS.log', 'force_assets_load': False, 'no_load_cache': False, 'configfile': ['config'], 'syslog_address': None, 'force_platform': None, 'bcp': False, 'pause': False, 'consoleloglevel': 20}
2018-04-02 10:38:23,866 : Machine : MPF path: c:\python34\lib\site-packages\mpf
2018-04-02 10:38:23,866 : Machine : Machine path: D:\Dev\mpf\scottp
2018-04-02 10:38:23,866 : Machine : Platform: win32
2018-04-02 10:38:23,866 : Machine : Python executable location: c:\python34\python.exe
2018-04-02 10:38:23,866 : Machine : Python version: 3.4.4 (64-bit)
2018-04-02 10:38:24,037 : Machine : Loading config from original files
2018-04-02 10:38:24,086 : Machine : Machine config file #1: D:\Dev\mpf\scottp\config\config
2018-04-02 10:38:24,091 : Machine : Config file cache created: C:\Users\maddo\AppData\Local\Temp\f2725e9fdb5e5699b9561cedbbf1540fconfig
2018-04-02 10:38:24,104 : SmartMatrix : Connecting to SmartMatrix RGB DMD on COM6 baud 2500000
2018-04-02 10:38:24,104 : root : could not open port 'COM6': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\game.py", line 181, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 117, in __init__
    self._load_hardware_platforms()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 534, in _load_hardware_platforms
    self.add_platform(platform)
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 647, in add_platform
    hardware_platform(self))
  File "c:\python34\lib\site-packages\mpf\platforms\smartmatrix.py", line 28, in __init__
    self.machine.clock.loop.run_until_complete(self._connect())
  File "c:\python34\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "c:\python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python34\lib\site-packages\mpf\platforms\smartmatrix.py", line 63, in _connect
    self.reader, self.writer = yield from connector
  File "c:\python34\lib\site-packages\mpf\core\clock.py", line 132, in open_serial_connection
    **kwargs)
  File "c:\python34\lib\asyncio\coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "c:\python34\lib\site-packages\serial_asyncio\__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "c:\python34\lib\site-packages\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "c:\python34\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM6': FileNotFoundError(2, 'Le fichier spécifié est introuvable.', None, 2)
