2018-04-02 13:46:02,789 : Machine : Mission Pinball Framework Core Engine v0.33.49
2018-04-02 13:46:02,789 : Machine : Command line arguments: {'pause': False, 'configfile': ['config'], 'force_assets_load': False, 'force_platform': None, 'consoleloglevel': 20, 'logfile': 'logs\\2018-04-02-13-46-02-mpf-DESKTOP-U1P21TS.log', 'mpfconfigfile': 'c:\\python34\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'create_config_cache': True, 'mc_file_name': None, 'loglevel': 11, 'bcp': True, 'no_load_cache': False, 'syslog_address': None}
2018-04-02 13:46:02,789 : Machine : MPF path: c:\python34\lib\site-packages\mpf
2018-04-02 13:46:02,789 : Machine : Machine path: D:\Dev\mpf\scottp
2018-04-02 13:46:02,789 : Machine : Platform: win32
2018-04-02 13:46:02,789 : Machine : Python executable location: c:\python34\python.exe
2018-04-02 13:46:02,789 : Machine : Python version: 3.4.4 (64-bit)
2018-04-02 13:46:02,966 : Machine : Loading cached config: C:\Users\maddo\AppData\Local\Temp\f2725e9fdb5e5699b9561cedbbf1540fconfig
2018-04-02 13:46:02,976 : SmartMatrix : Connecting to SmartMatrix RGB DMD on COM6 baud 2500000
2018-04-02 13:46:02,999 : SwitchController : Loading the SwitchController
2018-04-02 13:46:03,042 : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.33.49', 'prev_value': 'MPF v0.33.49', 'change': False}
2018-04-02 13:46:03,042 : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.33.49, Config version:4, Show version: 4, BCP version:1.1', 'prev_value': 'MPF v0.33.49, Config version:4, Show version: 4, BCP version:1.1', 'change': False}
2018-04-02 13:46:03,042 : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.4.4', 'prev_value': '3.4.4', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.16299', 'prev_value': 'Windows-10-10.0.16299', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': 'Windows', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': '10', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.16299', 'prev_value': '10.0.16299', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': 'AMD64', 'change': False}
2018-04-02 13:46:03,043 : EventManager : Event: ======'init_phase_1'====== Args={}
2018-04-02 13:46:03,083 : Machine : Shutting down...
2018-04-02 13:46:03,083 : EventManager : Event: ======'shutdown'====== Args={}
2018-04-02 13:46:03,083 : asyncio : Unhandled error in exception handler
context: {'exception': AssertionError('Config validation error: Entry ball_devices:bd_trough:eject_coil:c_trough_eject is not valid. ',), 'message': "Exception in callback EventManager._done(<Task finishe...ot valid. ',)>)", 'handle': <Handle EventManager._done(<Task finishe...ot valid. ',)>)>}
Traceback (most recent call last):
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 572, in _done
    future.result()
  File "c:\python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 507, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\core\device_manager.py", line 80, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\python34\lib\site-packages\mpf\core\device_manager.py", line 126, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\python34\lib\site-packages\mpf\core\device.py", line 68, in validate_and_parse_config
    self.config_section, config, self.name, "device")
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 205, in validate_config_item
    validation_failure_info)
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 565, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 327, in _validate_type_machine
    self.validation_error(item, validation_failure_info)
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 582, in validation_error
    item, msg))
AssertionError: Config validation error: Entry ball_devices:bd_trough:eject_coil:c_trough_eject is not valid. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\asyncio\base_events.py", line 1122, in call_exception_handler
    self._exception_handler(self, context)
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 143, in _exception_handler
    self.stop()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 709, in stop
    self.events.process_event_queue()
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 615, in process_event_queue
    **event[3])
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 584, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 543, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 146, in stop
    self.ball_count_handler.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
2018-04-02 13:46:10,433 : Machine : Shutting down...
2018-04-02 13:46:10,433 : EventManager : Event: ======'shutdown'====== Args={}
2018-04-02 13:46:10,433 : asyncio : Unhandled error in exception handler
context: {'exception': SerialException("ClearCommError failed (PermissionError(13, 'Le périphérique ne reconnaît pas la commande.', None, 22))",), 'message': 'Exception in callback SerialTransport._poll_read()', 'handle': <TimerHandle when=872424.6565 SerialTransport._poll_read()>}
Traceback (most recent call last):
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\python34\lib\site-packages\serial_asyncio\__init__.py", line 275, in _poll_read
    if self.serial.in_waiting:
  File "c:\python34\lib\site-packages\serial\serialwin32.py", line 257, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Le périphérique ne reconnaît pas la commande.', None, 22))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\asyncio\base_events.py", line 1122, in call_exception_handler
    self._exception_handler(self, context)
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 143, in _exception_handler
    self.stop()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 709, in stop
    self.events.process_event_queue()
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 615, in process_event_queue
    **event[3])
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 584, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 543, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 146, in stop
    self.ball_count_handler.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
